#!/usr/bin/env sh
simName="simA"
card="MAX3424A"
make mesh_fpga_sim
maxcompilersim -n $simName stop
maxcompilersim -n $simName -c $card start
./mesh_fpga_sim ${simName}0:${simName} sim
#maxcompilersim -n $simName stop
